name: Deploy Node.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > chiptunning.pem
          chmod 600 chiptunning.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i chiptunning.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo su
            cd /var/www/chiptuning_backend_nodejs_local
            git pull origin main
            npm install
            pm2 restart 0
            
          EOF
